server:
  port: 6781
eureka:
  client:
    service-url: 
        defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: gateway-zull6781
    prefer-ip-address: true
info: 
  message: "网关"
